let questions = {
    "avocado": "What is the primary ingredient in guacamole?",
    "Italy": "Which country is famous for its pasta dishes such as spaghetti and lasagna?",
    "burrito": "What is the name of the Mexican dish consisting of a folded or rolled tortilla filled with various ingredients?",
    "Durian": "Which fruit is known as the “king of fruits” and is famous for its strong smell?",
    "Canberra": "What is the capital city of Australia?",
    "Cheetah": "What is the fastest land animal?",
    "Gravity": "What is the force that pulls objects toward the center of the Earth?",
    "Friction": "What is the force that opposes motion between two surfaces in contact?",
    "Nitrogen": "Which gas makes up the majority of Earth’s atmosphere?",
    "Einstein": "Who is known as the father of modern physics and developed the theory of relativity?",
    "Fleming": "Who discovered penicillin, revolutionizing medicine with the first widely used antibiotic?",
    "Newton": "Who formulated the laws of motion and universal gravitation?",
    "Cobra": "Which venomous snake is known for its hood and deadly bite?",
    "Firefly": "Which insect is known for its ability to produce light through bioluminescence?",
    "Giraffe": "Which animal is known for its long neck and spots on its coat?",
    "Octopus": "Which sea creature is known for its eight arms and a beak?",
    "Capybara": "What is the world’s largest rodent?",
    "Darwin": "Which scientist is famous for his theory of evolution by natural selection?",
    "Hindi": "What is the official language of India?",
    "Russia": "Which country is the largest by land area in the world?",
    "Thailand": "Which Southeast Asian country is known as the Land of Smiles?",
    "Jordan": "In which country would you find the ancient city of Petra?",
    "Japan": "Which country is known as the Land of the Rising Sun?",
    "Cabbage": "What is the main ingredient of the Korean side dish, “kimchi”?",
    "Baikal": "What is the largest lake in the world?",
    "Mercury": "What chemical element is designated as “Hg”?",
    "Baguette": "What is the most popular bread in France?",
    "Brazil": "Which county is the biggest grower of coffee?",
    "Chicago": "Which city is called the “City of Winds”?",
}

export default questions